### ISSUE TITLE
Support custom task as part of build process

### ISSUE THREAD

**Issue by mpaulweeks** [vaguevoid/actions#14]
When building for web, I have a step where I run `npm run timestamp` which creates a git-ignored JSON file with the latest commit info. This gives my app a static file it can fetch to figure out when the build was made, without having to duplicate such easily inferable information in source.

This works fine with `share/on/web` because I can run my own build + timestamp before invoking the action. However, the current steam deploy process is a black box. Please provide a way for me to run arbitrary CLI commands after checkout but before packaging the game files.

**Comment by jakesgordon** [comment]
@mpaulweeks - I've added support for specifying an (optional) `prebuild` task that will be run before building the game in both the `share/on/web` and `share/on/steam` actions.

So, you should now be able to update your GitHub workflow and add `prebuild: timestamp` to the action inputs

```yaml
      - name: Build, Package, and Deploy to Steam
        uses: vaguevoid/actions/share/on/steam@alpha
        with:
          prebuild: "timestamp"      # run this task before building game
          // ...
```
